apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  labels:
    app: blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: blog-app
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 5000
          env:
            - name: APP_PATH
              value: blog-service
            - name: ANALYZER_URL
              value: http://text-analyze-svc:3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-analyze-service
  labels:
    app: text-analyze-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-analyze-service
  template:
    metadata:
      labels:
        app: text-analyze-service
    spec:
      containers:
        - name: text-analyze-service
          image: blog-app
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8085
          env:
            - name: APP_PATH
              value: text-analyze-service
---

apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  labels:
    app: blog-svc
spec:
  type: NodePort
  selector:
    app: blog-service
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: text-analyze-svc
  labels:
    app: text-analyze-svc
spec:
  selector:
    app: text-analyze-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
